name: Makefile CI

on:
  push:
    tags: ['[0-9].[0-9]+.[0-9]+']
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: sudo make deps

    - name: Build
      run: make

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: rootfs
        path: rootfs.tar.gz

  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
    - uses: actions/download-artifact@v3
      with:
        name: rootfs
        path: rootfs.tar.gz

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} 
        asset_path: ./rootfs.tar.gz
        asset_name: rootfs.tar.gz
        asset_content_type: application/gzip
