name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: sudo make deps

    - name: Build
      run: make

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: rootfs
        path: rootfs.tar.gz
